agentomics-ml:
  start: agentomics-ml/start.sh
  dockerfile: agentomics-ml/Dockerfile
  env_vars:
    # OPENROUTER_API_KEY: 
    # pass wandb keys for logging
    # WANDB_API_KEY: ""
    # WANDB_PROJECT_NAME: ""
    # WANDB_ENTITY: ""

    #TODO configure these before running experiments
    NVIDIA_VISIBLE_DEVICES: all
    SPLIT_ALLOWED_ITERATIONS: 1
    ITERATIONS: 1
    MODEL: openai/gpt-5-mini
    USER_PROMPT: "Create a machine learning model that will generalize to new unseen data."

