name: agentomics-env
channels:
  - conda-forge
dependencies:
  - python==3.10
  - pandas
  - ipykernel
  - ipywidgets
  - jupyter
  - pydantic-ai==0.0.46
  - pip
  - pip:
    - smolagents
    - smolagents[litellm]
    - langchain
    - langchain-community
    - scikit-learn
    - wandb
    - hrid
    - timeout-function-decorator