name: multiagent-ml-env
channels:
  - conda-forge
dependencies:
  - python==3.10
  - pandas
  - ipykernel
  - ipywidgets
  - jupyter
  - pip
  - pip:
    - smolagents
    - smolagents[litellm]
    - langchain
    - langchain-community
    - scikit-learn
    - wandb
