biomlbench_repo: https://github.com/dimostzim/biomlbench.git
biomlbench_branch: main

openrouter_key: sk-or-v1
openrouter_base_url: https://openrouter.ai/api/v1

time_limit_secs: 1800
step_limit: 99999999  #  unlimited - agents controlled by time_limit_secs only

agents:
  aide:
    model: openai/gpt-5-codex
  biomni:
    model: openai/gpt-5-codex
    self_critic: true
    iterations: 99999999
  stella:
    model: openai/gpt-5-codex
  oneshot:
    model: openai/gpt-5-codex

datasets:
  - ago2_clash_hejret
  - drosophila_enhancers_stark
  - human_enhancers_cohn
  - human_enhancers_ensembl
  - human_ocr_ensembl